### ISSUE TITLE
Capable of listing all windows on a desktop?

### ISSUE THREAD

**Issue by fiskhest** [andreykaere/ixwindow#1]
I'm looking for a module capable of rendering the icons of all windows in each desktop at any given moment. I skimmed the readme and source code for this module and it seems it only renders the icon of the currently focused window?

**Comment by andreykaere** [comment]
Well, I was inspired by icon feature from awesome-wm and I thought it could be cool to integrate this feature into polybar as well. However in awesome it shows icon and name of window for every window on the current desktop and it makes sense due to its additional functionality (like hiding windows), than just a decorative. 

At first I was annoyed by bar in awesome being filled with "tabs" of windows, however I like the hiding feature there. So in general it might be a good idea implementing this feature in the future, but for now it's not technically possible (see the reason below). So, without additional features I don't see the point in filling bar with icons ...

P.S. Further more, for now I think that's impossible to do on polybar, since I can't even integrate images there directly and as you might notice, you have to specify coordinates for the icon yourself, because there is no way to calculate them from the external program.

**Comment by fiskhest** [comment]
I was worried that was the case, thanks for clarifying.
