### ISSUE TITLE
Attempting to run script leads to thread panic. 

### ISSUE THREAD

**Issue by mauricioquintela** [andreykaere/ixwindow#3]
Just discovered this script, currently trying to test it out on Arch. After carefully following the README, running the main process of ixwindow (wether through polybar or not) results in the main thread panicking and the script crashing. In attachment I included the full rust backtrace of the panic.
[backtrace.txt](https://github.com/andreykaere/ixwindow/files/10785752/backtrace.txt)

**Comment by andreykaere** [comment]
Hi! Thank you for bringing it up! It seems, something is wrong with detection `generate-icon` file. Can you, please, provide your installation profile for i3?

**Comment by mauricioquintela** [comment]
Hey, no worries. i3 version returns `i3 version 4.22 (2023-01-02)`. I'm not sure what the "installation profile" for i3 is? Is it the config file?

**Comment by andreykaere** [comment]
When you install, you have `profiles` folder, where you can modify files `bspwm.toml` and `i3.toml`. Did you modify the latter? If so, kindly send it, so that I can reproduce the issue.

If you didn't modify, then check if there is file `generate-icon` in `~/.config/polybar/scripts/ixwindow` folder. If it's not there, and you didn't change installation profile (`i3.toml`), than it's weird. It would be helpful if you could find it (you can do it for example with `find . -name "generate-icon"`). If it will find it, please, tell me the location. If not, let me know that it's just not on your system.

**Comment by mauricioquintela** [comment]
Oh, those profile files. I did not touch them when installing. 

There is indeed a `generate-icon` file in `~/.config/polybar/scripts/ixwindow`, as expected.

**Comment by andreykaere** [comment]
Okay, I found what's causing the problem. Will deliver a patch for it with next commit! Thank you again for drawing my attention to it!

**Comment by mauricioquintela** [comment]
Thank you for your help as well. Looking forward to testing the script myself :)

**Comment by andreykaere** [comment]
Let me know how it works out for you!:)
